name: PR_Test

on:
  pull_request:
    branches: [ main ]

jobs:
  show_info:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Echo data
        run: | 
          echo "HEAD ${{ github.head_ref }}"
          echo "TARGET ${{ github.base_ref }}"
          echo "EVENT ${{ github.event.pull_request.head.repo.git_url }}"
          echo "SHA ${{ github.event.pull_request.head.sha }}"
          echo "SECRET VALUE ${{ secrets.TEST_VALUE }}"
